version: '2.1'

services:
  isomorphic-react-boilerplate:
    image: isomorphic-react-boilerplate
    build:
      context: .
      dockerfile: ./.docker/dev.Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
