version: '2.1'

services:
  node:
    image: isomorphic-react-boilerplate
    build:
      context: .
      dockerfile: ./.docker/node.development.dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./logs:/usr/src/app/logs
      - ./src:/usr/src/app/src
    ports:
      - 3000:3000
