version: '2.1'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./.docker/nginx.production.dockerfile
    ports:
      - 80:80
    links:
      - node:node
    networks:
      - isomorphic-react-boilerplate-network

  node:
    image: isomorphic-react-boilerplate
    build:
      context: .
      dockerfile: ./.docker/node.production.Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - isomorphic-react-boilerplate-network

networks:
  isomorphic-react-boilerplate-network:
    driver: bridge
