version: '2.1'

services:
  isomorphic-react-boilerplate:
    image: isomorphic-react-boilerplate
    build:
      context: .
      dockerfile: ./.docker/node.development.dockerfile
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      DEBUG: api
    volumes:
      - ./logs:/usr/src/app/logs
      - ./src:/usr/src/app/src
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run debug
    #command: node --inspect=0.0.0.0:9229 ./dist/server/index.js
